### ISSUE TITLE
Some LTLAs appearing grey in map

### ISSUE THREAD

**Issue by FoursACrowdKeele** [FoursACrowdKeele/CVD-19_Mapping#5]
Some LTLAs appearing as grey on the map, possibly becuase there is not a ltla code to join to in the covid-19 dataset.

**Comment by FoursACrowdKeele** [comment]
Need to swap load to 2019 ltla file

**Comment by d-childs** [comment]
We were previously using a map boundary file which contained the LTLA boundaries as at April 2021 - however the covid case data references LTLAs as they were at April 2019. I have uploaded the boundaries for 2019 and adjusted the data load to reflect this
